apiVersion: v1
kind: Service
metadata:
  name: keycloak-proxy
  namespace: {{ .Release.Namespace | default "keycloak" }}
  labels:
    app: keycloak-proxy
    {{- include "keycloak.labels" . | nindent 4 }}
spec:
  ports:
    - protocol: TCP
      port: 8090
      targetPort: proxy-http
      name: proxy-http
  selector:
    app: keycloak-proxy
    {{- include "keycloak.selectorLabels" . | nindent 4 }}
  type: ClusterIP  # 集群内访问，网关可通过这个 Service 调用

