apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: keycloak
  namespace: {{ .Release.Namespace | default "keycloak" }}
  labels:
    app: keycloak
    {{- include "keycloak.labels" . | nindent 4 }}
spec:
  serviceName: keycloak-discovery
  replicas: {{ .Values.keycloak.replicas }}  # 从values取副本数
  selector:
    matchLabels:
      app: keycloak
      {{- include "keycloak.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: keycloak
        {{- include "keycloak.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: keycloak
          image: "{{ .Values.keycloak.image.repository }}:{{ .Values.keycloak.image.tag }}"  # 从values取镜像
          args: ["start"]
          env:
            - name: KC_BOOTSTRAP_ADMIN_USERNAME
              value: "{{ .Values.keycloak.admin.username }}"  # 管理员用户名
            - name: KC_BOOTSTRAP_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.keycloak.admin.secretName }}
                  key: {{ .Values.keycloak.admin.passwordKey }}
            - name: KC_PROXY_HEADERS
              value: "{{ .Values.keycloak.config.proxyHeaders }}"
            - name: KC_HTTP_ENABLED
              value: "{{ .Values.keycloak.config.httpEnabled }}"
            - name: KC_HOSTNAME_STRICT
              value: "{{ .Values.keycloak.config.hostnameStrict }}"
            - name: KC_HEALTH_ENABLED
              value: "{{ .Values.keycloak.config.healthEnabled }}"
            - name: KC_CACHE
              value: "{{ .Values.keycloak.config.cache }}"
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: KC_CACHE_EMBEDDED_NETWORK_BIND_ADDRESS
              value: '$(POD_IP)'
            - name: KC_DB_URL_DATABASE
              value: "{{ .Values.keycloak.config.db.database }}"
            - name: KC_DB_URL_HOST
              value: "{{ .Values.keycloak.config.db.host }}"
            - name: KC_DB
              value: "{{ .Values.keycloak.config.db.type }}"
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.keycloak.config.db.secretName }}
                  key: {{ .Values.keycloak.config.db.passwordKey }}
            - name: KC_DB_USERNAME
              value: "{{ .Values.keycloak.config.db.username }}"
          ports:
            - name: http
              containerPort: 8080
            - name: jgroups
              containerPort: 7800
            - name: jgroups-fd
              containerPort: 57800
            - name: health
              containerPort: 9000
          startupProbe:
            httpGet:
              path: /health/started
              port: 9000
            periodSeconds: 1
            failureThreshold: 600
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 9000
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health/live
              port: 9000
            periodSeconds: 10
            failureThreshold: 3
          resources:
            limits:
              cpu: {{ .Values.keycloak.resources.limits.cpu }}
              memory: {{ .Values.keycloak.resources.limits.memory }}
            requests:
              cpu: {{ .Values.keycloak.resources.requests.cpu }}
              memory: {{ .Values.keycloak.resources.requests.memory }}

