apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres
    {{- include "keycloak.labels" . | nindent 4 }}
  name: postgres
  namespace: {{ .Release.Namespace | default "keycloak" }}
spec:
  selector:
    app: postgres
    {{- include "keycloak.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.postgres.port }}
      targetPort: {{ .Values.postgres.port }}
  type: ClusterIP

