apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: {{ .Release.Namespace | default "keycloak" }}
  labels:
    app: postgres
    {{- include "keycloak.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.postgres.replicas }}  # 从values取副本数
  selector:
    matchLabels:
      app: postgres
      {{- include "keycloak.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: postgres
        {{- include "keycloak.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}"  # 从values取镜像
          env:
            - name: POSTGRES_USER
              value: "{{ .Values.postgres.auth.username }}"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.auth.secretName }}
                  key: {{ .Values.postgres.auth.passwordKey }}
            - name: POSTGRES_DB
              value: "{{ .Values.postgres.auth.database }}"
            - name: POSTGRES_LOG_STATEMENT
              value: "all"
          ports:
            - name: postgres
              containerPort: {{ .Values.postgres.port }}
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data

