apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: backstage-postgres-local
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: false
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: backstage-postgres-server-00
  labels:
    app.kubernetes.io/part-of: model-platform
    app.kubernetes.io/component: backstage-postgres
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: backstage-postgres-local
  claimRef:
    namespace: backstage
    name: postgres-data-backstage-postgres-0
  local:
    path: /mnt/data/model-platform/backstage/postgresql
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - server-00
