{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "k12-clean-qa.serviceAccountName" . }}
  namespace: {{ include "k12-clean-qa.namespace" . }}
  labels:
    {{- include "k12-clean-qa.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
