# Slim image: code-only, requires base-opal-proxy as base
ARG BASE_IMAGE=base-opal-proxy:v1
FROM ${BASE_IMAGE}

COPY pep-proxy/app /app/pep_proxy
COPY bundle-server/app /app/bundle_server
RUN touch /app/pep_proxy/__init__.py /app/bundle_server/__init__.py

COPY pep-proxy/proto /app/proto
RUN python -m grpc_tools.protoc \
    -I/app/proto \
    --python_out=/app \
    --grpc_python_out=/app \
    /app/proto/ext_authz.proto

COPY data /app/data
COPY supervisord.conf /etc/supervisord.conf
