apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: model-platform-configmaps-aggregate-to-crossplane
  labels:
    app.kubernetes.io/part-of: model-platform
    app.kubernetes.io/component: deployment-api
    rbac.crossplane.io/aggregate-to-crossplane: "true"
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
