apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: model-serving
resources:
  - kubernetes.yaml
configMapGenerator:
  - name: model-deployment-cache-reaper
    files:
      - reap_orphan_cache_pods.py
generatorOptions:
  disableNameSuffixHash: true
