apiVersion: v1
kind: Secret
metadata:
  name: keycloak-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
type: Opaque
data:
  admin-password: {{ .Values.keycloak.admin.password | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
type: Opaque
data:
  postgres-password: {{ .Values.postgres.auth.password | b64enc }}
