apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: model-platform-deployment-requests
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: model-platform
    app.kubernetes.io/managed-by: kubectl
spec:
  project: model-platform-control-plane
  source:
    repoURL: http://gitea-http.gitea.svc.cluster.local:3000/gitadmin/model-platform-config.git
    targetRevision: main
    path: environments/production/modeldeployments
    directory:
      recurse: false
      include: '*.yaml'
  destination:
    server: https://kubernetes.default.svc
    namespace: model-serving
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
      allowEmpty: false
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 2m
    syncOptions:
      - CreateNamespace=false
      - ApplyOutOfSyncOnly=true
