apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kcc.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "kcc.labels" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.runtimeServiceAccount }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "kcc.labels" . | nindent 4 }}

