apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - upstream/release-v0.81.0.yaml
patches:
  - path: namespace-patch.yaml
  - path: autoinstall-patch.yaml
  - path: operator-patch.yaml
  - path: webhook-patch.yaml
