apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - resource-policy.yaml
  - rbac.yaml
  - network-policy.yaml
  - pipeline.yaml
  - triggers.yaml
  - backstage-pr-ci.yaml
  - k12-pipeline.yaml
  - k12-triggers.yaml
  - k12-gitops-validation.yaml
