{{- if and .Values.rbac.create .Values.rbac.exporterReader.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "kcc-training.fullname" . }}-exporter-reader
  namespace: {{ .Values.rbac.exporterReader.namespace }}
  labels:
    {{- include "kcc-training.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods/proxy"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kcc-training.fullname" . }}-exporter-reader
  namespace: {{ .Values.rbac.exporterReader.namespace }}
  labels:
    {{- include "kcc-training.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kcc-training.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "kcc-training.fullname" . }}-exporter-reader
{{- end }}
