{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kcc-training.fullname" . }}
  labels:
    {{- include "kcc-training.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kcc-training.fullname" . }}
  labels:
    {{- include "kcc-training.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kcc-training.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kcc-training.fullname" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "kcc-training.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kcc-training.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["configmaps", "events", "services", "pods"]
    verbs: ["get", "list", "create", "patch", "update", "delete"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
  - apiGroups: ["ray.io"]
    resources: ["rayclusters"]
    verbs: ["get", "list", "create", "patch", "update", "delete"]
  - apiGroups: ["scheduling.volcano.sh"]
    resources: ["podgroups"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kcc-training.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kcc-training.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kcc-training.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "kcc-training.fullname" . }}
{{- end }}
