{{- if .Values.credentials.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.credentials.existingSecret }}
  labels:
    {{- include "data-lake.labels" . | nindent 4 }}
type: Opaque
stringData:
  MINIO_ROOT_USER: {{ required "credentials.rootUser is required" .Values.credentials.rootUser | quote }}
  MINIO_ROOT_PASSWORD: {{ required "credentials.rootPassword is required" .Values.credentials.rootPassword | quote }}
{{- if and .Values.minio.enabled (ne .Values.minio.namespace .Release.Namespace) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.credentials.existingSecret }}
  namespace: {{ .Values.minio.namespace }}
  labels:
    {{- include "data-lake.labels" . | nindent 4 }}
type: Opaque
stringData:
  MINIO_ROOT_USER: {{ required "credentials.rootUser is required" .Values.credentials.rootUser | quote }}
  MINIO_ROOT_PASSWORD: {{ required "credentials.rootPassword is required" .Values.credentials.rootPassword | quote }}
{{- end }}
{{- end }}
