apiVersion: v1
kind: ServiceAccount
metadata: {name: {{ include "kcc.fullname" . }}, namespace: {{ .Release.Namespace }}}
---
apiVersion: v1
kind: ServiceAccount
metadata: {name: {{ .Values.runtimeServiceAccount }}, namespace: {{ .Release.Namespace }}}

