apiVersion: v1
kind: ServiceAccount
metadata:
  name: k12-data-pipeline-dagster
  namespace: k12-data-pipeline
  labels:
    app.kubernetes.io/part-of: model-platform
    app.kubernetes.io/component: dagster
automountServiceAccountToken: false
